services:
  app:
    build: .
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - app_shared_network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app_shared_network

  composer:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - app_shared_network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: xxx
      MYSQL_DATABASE: xxx
      MYSQL_USER: xxx
      MYSQL_PASSWORD: xxx
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_shared_network

volumes:
  mysql_data:

networks:
  app_shared_network:
    external: true
